// LifeSim game data, generated from the iOS app (LifeSim/Core/Models.swift and Careers.swift).
"use strict";
const jobCatalog = [
    {id: "babysitter", title: "Babysitter", baseSalary: 6_000, minAge: 14, partTime: true},
    {id: "cashier", title: "Cashier", baseSalary: 9_000, minAge: 15, partTime: true},
    {id: "lifeguard", title: "Lifeguard", baseSalary: 8_500, minAge: 15, partTime: true},
    {id: "dogwalker", title: "Dog Walker", baseSalary: 5_000, minAge: 14, partTime: true},

    {id: "janitor", title: "Janitor", baseSalary: 26_000},
    {id: "fastfood", title: "Fast Food Worker", baseSalary: 22_000},
    {id: "barista", title: "Barista", baseSalary: 24_000},
    {id: "construction", title: "Construction Worker", baseSalary: 38_000},
    {id: "trucker", title: "Truck Driver", baseSalary: 48_000},
    {id: "receptionist", title: "Receptionist", baseSalary: 32_000, requiredEducation: 'highSchool'},
    {id: "police", title: "Police Officer", baseSalary: 55_000, requiredEducation: 'highSchool', minSmarts: 30},
    {id: "firefighter", title: "Firefighter", baseSalary: 52_000, requiredEducation: 'highSchool'},
    {id: "model", title: "Fashion Model", baseSalary: 60_000, minLooks: 80},
    {id: "teacher", title: "Teacher", baseSalary: 50_000, requiredMajor: "Education"},
    {id: "nurse", title: "Nurse", baseSalary: 72_000, requiredMajor: "Nursing"},
    {id: "engineer", title: "Mechanical Engineer", baseSalary: 85_000, requiredMajor: "Engineering", minSmarts: 50},
    {id: "software", title: "Software Engineer", baseSalary: 110_000, requiredMajor: "Computer Science", minSmarts: 55},
    {id: "accountant", title: "Accountant", baseSalary: 65_000, requiredEducation: 'bachelor', minSmarts: 40},
    {id: "marketing", title: "Marketing Associate", baseSalary: 58_000, requiredEducation: 'bachelor'},
    {id: "psych", title: "Psychologist", baseSalary: 82_000, requiredMajor: "Psychology", minSmarts: 50},
    {id: "doctor", title: "Doctor", baseSalary: 210_000, requiredEducation: 'graduate', requiredField: 'medicine', minSmarts: 70},
    {id: "lawyer", title: "Lawyer", baseSalary: 140_000, requiredEducation: 'graduate', requiredField: 'law', minSmarts: 60},
    {id: "banker", title: "Investment Banker", baseSalary: 160_000, requiredEducation: 'graduate', requiredField: 'business', minSmarts: 60},
    {id: "chef", title: "Line Cook", baseSalary: 30_000},
    {id: "pilot", title: "Airline Pilot", baseSalary: 130_000, requiredEducation: 'bachelor', minSmarts: 55},
    {id: "scientist", title: "Research Scientist", baseSalary: 95_000, requiredMajor: "Biology", minSmarts: 65},
    {id: "soldier", title: "Army Private", baseSalary: 32_000, minSmarts: 0, military: true, maxAge: 35, minHealth: 50},
    {id: "actor", title: "Actor", baseSalary: 25_000, minLooks: 50, famous: true},
    {id: "musician", title: "Musician", baseSalary: 20_000, famous: true},
    {id: "athlete", title: "Pro Athlete", baseSalary: 60_000, famous: true, maxAge: 32, minHealth: 80},
];
const careerLadders = {
    "babysitter": ["Babysitter", "Nanny"],
    "cashier": ["Cashier", "Head Cashier"],
    "lifeguard": ["Junior Lifeguard", "Lifeguard", "Head Lifeguard"],
    "dogwalker": ["Dog Walker", "Pack Leader"],
    "janitor": ["Janitor", "Head Custodian", "Facilities Manager"],
    "fastfood": ["Fry Cook", "Shift Leader", "Assistant Manager", "Restaurant Manager"],
    "barista": ["Barista", "Shift Supervisor", "Café Manager"],
    "construction": ["Laborer", "Carpenter", "Foreman", "Site Manager"],
    "trucker": ["Truck Driver", "Senior Driver", "Fleet Manager"],
    "receptionist": ["Receptionist", "Office Coordinator", "Office Manager"],
    
    "police": ["Police Cadet", "Police Officer"],
    "firefighter": ["Firefighter Recruit", "Firefighter", "Engineer", "Fire Lieutenant", "Fire Captain", "Fire Chief"],
    "model": ["Catalog Model", "Runway Model", "Fashion Model", "Supermodel"],
    "teacher": ["Substitute Teacher", "Teacher", "Department Head", "Vice Principal", "Principal"],
    "nurse": ["Nursing Assistant", "Registered Nurse", "Charge Nurse", "Head Nurse", "Director of Nursing"],
    "engineer": ["Junior Engineer", "Mechanical Engineer", "Senior Engineer", "Principal Engineer", "Chief Engineer"],
    "software": ["Junior Developer", "Software Engineer", "Senior Engineer", "Staff Engineer", "Principal Engineer", "CTO"],
    "accountant": ["Junior Accountant", "Accountant", "Senior Accountant", "Controller", "CFO"],
    "marketing": ["Marketing Assistant", "Marketing Associate", "Marketing Manager", "Marketing Director", "CMO"],
    "psych": ["Psychology Intern", "Psychologist", "Senior Psychologist", "Clinical Director"],
    "doctor": ["Resident", "Doctor", "Attending Physician", "Department Head", "Chief of Medicine"],
    "lawyer": ["Junior Associate", "Associate", "Senior Associate", "Partner", "Managing Partner"],
    "banker": ["Analyst", "Associate", "Vice President", "Director", "Managing Director"],
    "chef": ["Dishwasher", "Line Cook", "Sous Chef", "Head Chef", "Executive Chef"],
    "pilot": ["Flight Cadet", "First Officer", "Captain", "Senior Captain", "Chief Pilot"],
    "scientist": ["Lab Assistant", "Research Scientist", "Senior Scientist", "Lead Scientist", "Chief Scientist"],
    "soldier": ["Private", "Corporal", "Sergeant", "Lieutenant", "Captain", "Major", "Colonel", "General"],
    "actor": ["Extra", "Bit Part Actor", "Supporting Actor", "Lead Actor", "Movie Star", "Hollywood Legend"],
    "musician": ["Street Musician", "Bar Musician", "Opening Act", "Headliner", "Rock Star", "Music Legend"],
    "athlete": ["Rookie", "Starter", "Team Captain", "All-Star", "MVP"],
};
const careerBranches = {
    "police": {atLevel: 2, tracks: [
        {id: "patrol", name: "Patrol", emoji: "🚓",
                    blurb: "Stay on the streets and rise through the uniformed ranks to run the whole department.",
                    titles: ["Patrol Sergeant", "Patrol Lieutenant", "Patrol Captain", "Deputy Chief", "Police Chief"]},
        {id: "detective", name: "Detective", emoji: "🕵️",
                    blurb: "Trade the uniform for a badge and solve murders, robberies and cold cases.",
                    titles: ["Detective", "Senior Detective", "Detective Sergeant", "Detective Lieutenant", "Chief of Detectives"],
                    minSmarts: 55, payMultiplier: 1.1, selectivity: 0.6},
        {id: "swat", name: "SWAT", emoji: "🛡️",
                    blurb: "Join the elite tactical unit for hostage rescues, raids and high-risk warrants.",
                    titles: ["SWAT Operator", "SWAT Team Leader", "SWAT Sergeant", "SWAT Lieutenant", "SWAT Commander"],
                    minHealth: 75, payMultiplier: 1.2, selectivity: 0.5},
    ]},
};
const commonJobActions = [
    {id: "hard", title: "Work Harder", emoji: "💼", successChance: 0.9,
              success: "I put in extra hours and my boss noticed.", failure: "I worked late but made a bunch of mistakes.",
              performance: 9, happiness: -2},
    {id: "coworkers", title: "Hang Out with Coworkers", emoji: "🍻", successChance: 0.8,
              success: "I went for drinks with my coworkers. We're getting along great.", failure: "I said something awkward at the office happy hour.",
              performance: 3, happiness: 6},
    {id: "slack", title: "Slack Off", emoji: "😴", successChance: 0.6,
              success: "I spent the day scrolling my phone and nobody noticed.", failure: "My boss caught me napping at my desk.",
              performance: -2, happiness: 8, firedRisk: 0.1},
];
const jobActions = {
    "babysitter": [
        {id: "games", title: "Play Games with the Kids", emoji: "🧸", success: "The kids had a blast and their parents tipped me.", failure: "The kids threw a tantrum the whole night.", performance: 8, happiness: 3, bonus: [10, 50]},
        {id: "tv", title: "Park Them in Front of the TV", emoji: "📺", successChance: 0.5, success: "The kids watched cartoons and I got some homework done.", failure: "The parents came home early and caught me ignoring their kids.", performance: -3, happiness: 4, firedRisk: 0.3},
    ],
    "cashier": [
        {id: "upsell", title: "Upsell Customers", emoji: "🛒", success: "I convinced a customer to buy the premium version.", failure: "A customer yelled at me for being pushy.", performance: 7},
        {id: "steal", title: "Skim from the Register", emoji: "💵", successChance: 0.6, success: "I pocketed some cash from the register.", failure: "My manager counted the drawer and caught me stealing!", performance: 0, bonus: [20, 200], karma: -5, firedRisk: 1.0},
    ],
    "lifeguard": [
        {id: "rescue", title: "Rescue a Swimmer", emoji: "🛟", successChance: 0.75, success: "I pulled a drowning kid out of the water. I'm a hero!", failure: "I swallowed a lot of water during a rescue attempt.", performance: 15, happiness: 8, karma: 5, injury: 6},
        {id: "tan", title: "Work on My Tan", emoji: "😎", successChance: 0.7, success: "I got a great tan in my lifeguard chair.", failure: "I got a nasty sunburn.", performance: -2, happiness: 5, injury: 4},
    ],
    "dogwalker": [
        {id: "pack", title: "Walk a Big Pack", emoji: "🐕", successChance: 0.65, success: "I walked eight dogs at once and earned extra.", failure: "The dogs dragged me through a puddle.", performance: 8, bonus: [20, 100], injury: 3},
    ],
    "janitor": [
        {id: "deep", title: "Deep Clean the Building", emoji: "🧹", success: "The building has never been this spotless.", failure: "I knocked over a full mop bucket in the lobby.", performance: 10},
        {id: "snoop", title: "Snoop Through Offices", emoji: "🕵️", successChance: 0.6, success: "I found some juicy gossip in the CEO's trash.", failure: "Security caught me rummaging through desks.", performance: 0, happiness: 6, firedRisk: 0.6},
    ],
    "fastfood": [
        {id: "rush", title: "Handle the Lunch Rush", emoji: "🍔", success: "I flipped 300 burgers without breaking a sweat.", failure: "I burned my hand on the fryer.", performance: 10, injury: 5},
        {id: "spit", title: "Mess with a Rude Customer's Order", emoji: "🤢", successChance: 0.6, success: "I got my revenge on a rude customer.", failure: "A coworker reported me to the manager.", performance: 0, happiness: 5, karma: -4, firedRisk: 0.8},
    ],
    "barista": [
        {id: "latte", title: "Make Latte Art", emoji: "☕", success: "Customers loved my latte art and tipped well.", failure: "My latte art looked like a blob.", performance: 7, happiness: 3, bonus: [20, 80]},
        {id: "freebies", title: "Give Friends Free Drinks", emoji: "🥤", successChance: 0.6, success: "My friends got free coffee all week.", failure: "My manager noticed the missing inventory.", performance: -1, happiness: 4, firedRisk: 0.4},
    ],
    "construction": [
        {id: "heavy", title: "Operate Heavy Machinery", emoji: "🚜", successChance: 0.7, success: "I operated the crane like a pro.", failure: "I had an accident with the excavator.", performance: 12, injury: 15, deathRisk: 0.03, deathCause: "a construction accident"},
        {id: "corners", title: "Cut Corners", emoji: "📐", successChance: 0.55, success: "We finished the job ahead of schedule.", failure: "An inspector found serious safety violations.", performance: 6, karma: -3, firedRisk: 0.4},
    ],
    "trucker": [
        {id: "overnight", title: "Drive Overnight", emoji: "🌙", successChance: 0.7, success: "I delivered my load a day early and got a bonus.", failure: "I dozed off at the wheel and crashed.", performance: 10, bonus: [500, 2_000], injury: 20, deathRisk: 0.05, deathCause: "a trucking accident"},
        {id: "contraband", title: "Smuggle Contraband", emoji: "📦", successChance: 0.55, success: "I hauled a mysterious crate across state lines for cash.", failure: "Police searched my truck at a weigh station.", performance: 0, bonus: [5_000, 20_000], karma: -6, prison: [2, 6]},
    ],
    "receptionist": [
        {id: "phones", title: "Juggle the Phones", emoji: "☎️", success: "I handled 200 calls without a single mistake.", failure: "I transferred the CEO's call to the janitor.", performance: 8},
        {id: "gossip", title: "Spread Office Gossip", emoji: "🗣️", successChance: 0.6, success: "Everyone comes to me for the latest gossip now.", failure: "My gossip got back to the person I was talking about.", performance: -2, happiness: 6, karma: -2, firedRisk: 0.15},
    ],
    "police": [
        {id: "beat", title: "Walk the Beat", emoji: "👮", successChance: 0.85, success: "I got to know the neighborhood and stopped a mugging.", failure: "A suspect got away from me.", performance: 8, karma: 2, injury: 4},
        {id: "bribe", title: "Take a Bribe", emoji: "💰", successChance: 0.6, success: "I let a dealer go in exchange for cash.", failure: "Internal Affairs caught me taking a bribe.", performance: 0, bonus: [2_000, 15_000], karma: -10, prison: [2, 8]},
    ],
    "police.patrol": [
        {id: "traffic", title: "Run Traffic Stops", emoji: "🚦", successChance: 0.85, success: "I wrote 40 tickets and caught a driver with a stolen car.", failure: "A driver I pulled over filed a complaint against me.", performance: 9},
        {id: "chase", title: "High-Speed Chase", emoji: "🏎️", successChance: 0.6, success: "I chased down a getaway car and made the arrest!", failure: "I crashed my cruiser during the chase.", performance: 15, fame: 1, injury: 15, deathRisk: 0.04, deathCause: "a high-speed police chase"},
        {id: "community", title: "Community Outreach", emoji: "🤝", successChance: 0.9, success: "I coached a youth basketball league. The neighborhood loves me.", failure: "Nobody showed up to my community meeting.", performance: 6, happiness: 5, karma: 4},
    ],
    "police.detective": [
        {id: "case", title: "Investigate a Case", emoji: "🔍", successChance: 0.65, success: "I followed the evidence and arrested the killer.", failure: "My lead suspect had an airtight alibi.", performance: 12, karma: 2},
        {id: "interrogate", title: "Interrogate a Suspect", emoji: "💡", successChance: 0.6, success: "I got a full confession in the interrogation room.", failure: "The suspect lawyered up and walked.", performance: 10},
        {id: "undercover", title: "Go Undercover", emoji: "🥸", successChance: 0.5, success: "I infiltrated a crime ring and brought them all down!", failure: "My cover was blown and the gang beat me badly.", performance: 22, fame: 3, injury: 30, deathRisk: 0.08, deathCause: "being discovered while undercover"},
        {id: "coldcase", title: "Crack a Cold Case", emoji: "🗄️", successChance: 0.35, success: "I solved a 20-year-old murder. It's all over the news!", failure: "The trail went cold again.", performance: 20, fame: 4, karma: 4, minLevel: 3},
        {id: "plant", title: "Plant Evidence", emoji: "🧤", successChance: 0.55, success: "I planted evidence to close a case I couldn't crack.", failure: "A defense attorney proved I planted evidence.", performance: 12, karma: -12, prison: [3, 10]},
    ],
    "police.swat": [
        {id: "breach", title: "Breach Training", emoji: "🧨", successChance: 0.85, success: "I led my squad through a flawless training breach.", failure: "A flashbang went off too close to me.", performance: 8, injury: 8},
        {id: "raid", title: "Lead a Drug Raid", emoji: "🚨", successChance: 0.6, success: "The raid was a success and made the evening news.", failure: "I was shot during the raid.", performance: 18, fame: 2, injury: 25, deathRisk: 0.08, deathCause: "a gunshot wound on duty"},
        {id: "hostage", title: "Rescue Hostages", emoji: "🛡️", successChance: 0.55, success: "I freed every hostage without a single casualty. I'm a hero!", failure: "The standoff went badly and I was wounded.", performance: 22, happiness: 8, fame: 4, karma: 5, injury: 30, deathRisk: 0.1, deathCause: "a hostage standoff"},
        {id: "sniper", title: "Sniper Overwatch", emoji: "🎯", successChance: 0.7, success: "I neutralized an armed gunman from 400 yards.", failure: "I missed the shot and the suspect escaped.", performance: 14, karma: -1, minLevel: 3},
    ],
    "firefighter": [
        {id: "fire", title: "Fight a Fire", emoji: "🔥", successChance: 0.7, success: "I put out a blazing apartment fire.", failure: "I suffered smoke inhalation.", performance: 12, karma: 3, injury: 15, deathRisk: 0.04, deathCause: "a burning building collapsing"},
        {id: "rescue", title: "Rescue Someone", emoji: "🧑‍🚒", successChance: 0.6, success: "I carried a family out of a burning house. Hero!", failure: "I got burned trying to reach someone.", performance: 18, happiness: 8, fame: 2, karma: 6, injury: 20},
        {id: "cat", title: "Rescue a Cat from a Tree", emoji: "🐈", successChance: 0.9, success: "I got a cat down from a tree. The kids cheered.", failure: "The cat scratched my face.", performance: 4, happiness: 4, karma: 2, injury: 2},
    ],
    "model": [
        {id: "photo", title: "Do a Photo Shoot", emoji: "📸", success: "The photographer said I was a natural.", failure: "I blinked in every shot.", performance: 10, fame: 2},
        {id: "runway", title: "Walk the Runway", emoji: "👠", successChance: 0.65, success: "I nailed my runway walk at fashion week!", failure: "I tripped on the runway in front of everyone.", performance: 14, fame: 4, injury: 3, minLevel: 1},
        {id: "diet", title: "Crash Diet for a Show", emoji: "🥬", successChance: 0.7, success: "I slimmed down for the big show.", failure: "I fainted from hunger backstage.", performance: 8, happiness: -4, injury: 10},
    ],
    "teacher": [
        {id: "lesson", title: "Plan a Great Lesson", emoji: "📝", success: "My students were actually excited about class today.", failure: "My lesson put the whole class to sleep.", performance: 9},
        {id: "detention", title: "Give Detention", emoji: "⏰", successChance: 0.7, success: "Order has been restored in my classroom.", failure: "The student's parents filed a complaint.", performance: 4, karma: -1},
        {id: "tutor", title: "Tutor After School", emoji: "🍎", success: "I tutored a struggling student for extra cash.", failure: "The student skipped our tutoring session.", performance: 5, bonus: [200, 800], karma: 2},
    ],
    "nurse": [
        {id: "double", title: "Work a Double Shift", emoji: "🏥", success: "I worked a 16-hour shift and saved a patient's life.", failure: "I was so exhausted I nearly collapsed.", performance: 12, happiness: -3, injury: 6},
        {id: "comfort", title: "Comfort a Patient", emoji: "🤲", successChance: 0.9, success: "I held a scared patient's hand all night.", failure: "The patient was too grumpy to talk.", performance: 6, happiness: 4, karma: 4},
        {id: "meds", title: "Pocket Some Painkillers", emoji: "💊", successChance: 0.55, success: "I slipped a bottle of painkillers into my bag.", failure: "The pharmacy audit caught me.", performance: 0, bonus: [500, 3_000], karma: -8, firedRisk: 1.0, prison: [1, 3]},
    ],
    "engineer": [
        {id: "design", title: "Design a New Part", emoji: "⚙️", success: "My design was approved for production.", failure: "My prototype failed stress testing.", performance: 10},
        {id: "patent", title: "File a Patent", emoji: "📜", successChance: 0.4, success: "My invention was patented and licensed!", failure: "My patent was rejected.", performance: 15, bonus: [5_000, 50_000], minLevel: 2},
    ],
    "software": [
        {id: "ship", title: "Ship a Feature", emoji: "🚀", success: "My feature launched without a single bug.", failure: "My code took down production for an hour.", performance: 10},
        {id: "hackathon", title: "Win a Hackathon", emoji: "🏆", successChance: 0.35, success: "My team won the company hackathon!", failure: "Our hackathon demo crashed on stage.", performance: 15, happiness: 6, bonus: [1_000, 10_000]},
        {id: "oncall", title: "Take On-Call Duty", emoji: "📟", successChance: 0.8, success: "I fixed a 3 AM outage in record time.", failure: "I slept through my pager.", performance: 8, happiness: -4, firedRisk: 0.05},
    ],
    "accountant": [
        {id: "audit", title: "Do an Audit", emoji: "🧾", success: "I found $2 million in accounting errors.", failure: "I miscounted a column and everything was off.", performance: 10},
        {id: "taxes", title: "Prepare Taxes on the Side", emoji: "📊", success: "I did taxes for neighbors and made some cash.", failure: "I filed a client's taxes wrong.", performance: 2, bonus: [1_000, 6_000]},
        {id: "embezzle", title: "Embezzle Funds", emoji: "🏦", successChance: 0.5, success: "I quietly moved company money into my account.", failure: "Forensic auditors traced the missing money to me.", performance: 0, bonus: [20_000, 200_000], karma: -12, prison: [3, 12]},
    ],
    "marketing": [
        {id: "campaign", title: "Launch a Campaign", emoji: "📣", success: "My ad campaign went viral!", failure: "My campaign was a flop.", performance: 12, fame: 1},
        {id: "pitch", title: "Pitch a Big Client", emoji: "🤝", successChance: 0.55, success: "I landed a huge new client.", failure: "The client walked out of my pitch.", performance: 15, bonus: [2_000, 10_000], minLevel: 1},
    ],
    "psych": [
        {id: "session", title: "Run a Therapy Session", emoji: "🛋️", success: "I helped a patient make a breakthrough.", failure: "My patient stormed out of our session.", performance: 9, karma: 2},
        {id: "paper", title: "Publish a Paper", emoji: "📄", successChance: 0.5, success: "My research paper was published in a top journal.", failure: "My paper was rejected by every journal.", performance: 14, fame: 2},
    ],
    "doctor": [
        {id: "surgery", title: "Perform Surgery", emoji: "🩺", successChance: 0.75, success: "The surgery was a complete success.", failure: "There were complications during surgery. The family is suing.", performance: 14, karma: 3, firedRisk: 0.1},
        {id: "rounds", title: "Do Hospital Rounds", emoji: "📋", successChance: 0.9, success: "I checked on every patient in the ward.", failure: "I mixed up two patients' charts.", performance: 7},
        {id: "research", title: "Lead a Clinical Trial", emoji: "🧪", successChance: 0.45, success: "My clinical trial led to a medical breakthrough!", failure: "The clinical trial was shut down.", performance: 20, fame: 4, bonus: [10_000, 50_000], minLevel: 2},
        {id: "pills", title: "Write Shady Prescriptions", emoji: "💊", successChance: 0.6, success: "I sold prescriptions under the table.", failure: "The medical board investigated me.", performance: 0, bonus: [10_000, 60_000], karma: -12, firedRisk: 1.0, prison: [2, 8]},
    ],
    "lawyer": [
        {id: "trial", title: "Argue a Case in Court", emoji: "⚖️", successChance: 0.6, success: "I won my case with a brilliant closing argument!", failure: "I lost the case and my client is furious.", performance: 15, fame: 1},
        {id: "settle", title: "Negotiate a Settlement", emoji: "🤝", successChance: 0.75, success: "I negotiated a fat settlement for my client.", failure: "Settlement talks fell apart.", performance: 9, bonus: [2_000, 15_000]},
        {id: "bill", title: "Pad My Billable Hours", emoji: "⏱️", successChance: 0.6, success: "I billed a client for 30 hours I didn't work.", failure: "The client noticed and reported me to the bar.", performance: 2, bonus: [5_000, 20_000], karma: -6, firedRisk: 0.7},
    ],
    "banker": [
        {id: "deal", title: "Close a Deal", emoji: "📈", successChance: 0.6, success: "I closed a billion-dollar merger and got a huge bonus.", failure: "The deal collapsed at the last minute.", performance: 15, bonus: [20_000, 150_000]},
        {id: "allnighter", title: "Pull an All-Nighter", emoji: "🌃", successChance: 0.85, success: "I finished the pitch deck by sunrise.", failure: "I passed out at my desk.", performance: 10, happiness: -6, injury: 6},
        {id: "insider", title: "Insider Trading", emoji: "🕴️", successChance: 0.55, success: "I traded on a tip and made a killing.", failure: "The SEC caught me insider trading.", performance: 0, bonus: [50_000, 500_000], karma: -10, prison: [2, 10]},
    ],
    "chef": [
        {id: "special", title: "Create a New Special", emoji: "🍝", success: "My new dish sold out in an hour.", failure: "Customers sent my special back to the kitchen.", performance: 10},
        {id: "critic", title: "Cook for a Food Critic", emoji: "⭐", successChance: 0.5, success: "The food critic gave us five stars!", failure: "The critic called my food 'inedible'.", performance: 18, fame: 3, minLevel: 2},
        {id: "knife", title: "Show Off Knife Skills", emoji: "🔪", successChance: 0.7, success: "I diced an onion in 4 seconds. The kitchen applauded.", failure: "I sliced my finger.", performance: 5, happiness: 3, injury: 6},
    ],
    "pilot": [
        {id: "fly", title: "Fly a Long-Haul Route", emoji: "✈️", success: "I flew to Tokyo and back with a perfect landing.", failure: "I had a rough landing and passengers complained.", performance: 9},
        {id: "emergency", title: "Handle an Emergency", emoji: "⚠️", successChance: 0.7, success: "I landed safely with one engine out. I'm on the news!", failure: "The plane went down.", performance: 20, fame: 5, deathRisk: 0.3, deathCause: "a plane crash"},
    ],
    "scientist": [
        {id: "experiment", title: "Run an Experiment", emoji: "🔬", success: "My experiment produced exciting results.", failure: "My experiment blew up in my face.", performance: 10, injury: 5},
        {id: "grant", title: "Apply for a Grant", emoji: "💸", successChance: 0.45, success: "I was awarded a major research grant!", failure: "My grant application was rejected.", performance: 14, bonus: [5_000, 40_000]},
        {id: "fake", title: "Fake My Data", emoji: "🧮", successChance: 0.6, success: "I fudged my results and published them.", failure: "Other scientists exposed my fake data.", performance: 12, karma: -8, firedRisk: 1.0},
    ],
    "soldier": [
        {id: "train", title: "Train Hard", emoji: "🏃", successChance: 0.85, success: "I aced my physical fitness test.", failure: "I pulled a muscle during training.", performance: 10, injury: 5},
        {id: "volunteer", title: "Volunteer for a Mission", emoji: "🪖", successChance: 0.65, success: "I completed a dangerous mission and earned a medal.", failure: "I was wounded in combat.", performance: 20, karma: 2, injury: 25, deathRisk: 0.1, deathCause: "wounds suffered in combat"},
        {id: "desert", title: "Go AWOL", emoji: "🏃‍♂️", successChance: 0.3, success: "I slipped away from base for a wild weekend.", failure: "Military police dragged me back and court-martialed me.", performance: -10, happiness: 10, prison: [1, 5]},
    ],
    "actor": [
        {id: "audition", title: "Audition for a Role", emoji: "🎬", successChance: 0.5, success: "I landed a role in a big movie!", failure: "The casting director said I wasn't right for it.", performance: 14, fame: 5, bonus: [5_000, 50_000]},
        {id: "redcarpet", title: "Walk the Red Carpet", emoji: "📸", successChance: 0.8, success: "The paparazzi went crazy for my outfit.", failure: "I made the worst-dressed list.", performance: 5, fame: 4, minLevel: 2},
        {id: "interview", title: "Do a Talk Show Interview", emoji: "🎙️", successChance: 0.7, success: "I had the audience in stitches.", failure: "I said something offensive and got canceled online.", performance: 8, fame: 3, minLevel: 1},
    ],
    "musician": [
        {id: "record", title: "Record a Song", emoji: "🎧", successChance: 0.6, success: "My new song is climbing the charts!", failure: "My new song got terrible reviews.", performance: 12, fame: 4, bonus: [1_000, 30_000]},
        {id: "tour", title: "Go on Tour", emoji: "🚌", successChance: 0.7, success: "I sold out every show on my tour!", failure: "Half my tour dates were canceled.", performance: 15, happiness: 5, fame: 5, bonus: [10_000, 200_000], injury: 4, minLevel: 2},
        {id: "practice", title: "Practice My Instrument", emoji: "🎸", successChance: 0.9, success: "My skills are getting better every day.", failure: "I broke a string mid-solo.", performance: 7},
    ],
    "athlete": [
        {id: "practice", title: "Practice with the Team", emoji: "🏟️", successChance: 0.85, success: "I dominated at practice today.", failure: "I sprained my ankle at practice.", performance: 9, injury: 8},
        {id: "game", title: "Play the Big Game", emoji: "🏅", successChance: 0.55, success: "I scored the winning point in the big game!", failure: "I choked in the big game and the fans booed me.", performance: 18, happiness: 8, fame: 5, injury: 6},
        {id: "steroids", title: "Take Steroids", emoji: "💉", successChance: 0.6, success: "I'm faster and stronger than ever.", failure: "I failed a drug test and was suspended.", performance: 15, karma: -6, injury: 8, firedRisk: 0.8},
    ],
};
