// LifeSim world: every country with its capital (listed first) and other major cities.
// A handful of micro-states have fewer than three real cities; Vatican City has only one.
"use strict";

const WORLD = [
  ["Afghanistan", ["Kabul", "Kandahar", "Herat"]],
  ["Albania", ["Tirana", "Durrës", "Vlorë"]],
  ["Algeria", ["Algiers", "Oran", "Constantine"]],
  ["Andorra", ["Andorra la Vella", "Escaldes-Engordany", "Encamp"]],
  ["Angola", ["Luanda", "Huambo", "Lobito"]],
  ["Antigua and Barbuda", ["St. John's", "All Saints", "Liberta"]],
  ["Argentina", ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"]],
  ["Armenia", ["Yerevan", "Gyumri", "Vanadzor"]],
  ["Australia", ["Canberra", "Sydney", "Melbourne", "Brisbane", "Perth"]],
  ["Austria", ["Vienna", "Graz", "Linz", "Salzburg"]],
  ["Azerbaijan", ["Baku", "Ganja", "Sumqayit"]],
  ["Bahamas", ["Nassau", "Freeport", "West End"]],
  ["Bahrain", ["Manama", "Riffa", "Muharraq"]],
  ["Bangladesh", ["Dhaka", "Chittagong", "Khulna"]],
  ["Barbados", ["Bridgetown", "Speightstown", "Oistins"]],
  ["Belarus", ["Minsk", "Gomel", "Mogilev"]],
  ["Belgium", ["Brussels", "Antwerp", "Ghent", "Bruges"]],
  ["Belize", ["Belmopan", "Belize City", "San Ignacio"]],
  ["Benin", ["Porto-Novo", "Cotonou", "Parakou"]],
  ["Bhutan", ["Thimphu", "Phuntsholing", "Paro"]],
  ["Bolivia", ["Sucre", "La Paz", "Santa Cruz de la Sierra"]],
  ["Bosnia and Herzegovina", ["Sarajevo", "Banja Luka", "Tuzla", "Mostar"]],
  ["Botswana", ["Gaborone", "Francistown", "Maun"]],
  ["Brazil", ["Brasília", "São Paulo", "Rio de Janeiro", "Salvador"]],
  ["Brunei", ["Bandar Seri Begawan", "Kuala Belait", "Seria"]],
  ["Bulgaria", ["Sofia", "Plovdiv", "Varna"]],
  ["Burkina Faso", ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"]],
  ["Burundi", ["Gitega", "Bujumbura", "Ngozi"]],
  ["Cabo Verde", ["Praia", "Mindelo", "Santa Maria"]],
  ["Cambodia", ["Phnom Penh", "Siem Reap", "Battambang"]],
  ["Cameroon", ["Yaoundé", "Douala", "Garoua"]],
  ["Canada", ["Ottawa", "Toronto", "Vancouver", "Montreal", "Calgary"]],
  ["Central African Republic", ["Bangui", "Bimbo", "Berbérati"]],
  ["Chad", ["N'Djamena", "Moundou", "Abéché"]],
  ["Chile", ["Santiago", "Valparaíso", "Concepción"]],
  ["China", ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"]],
  ["Colombia", ["Bogotá", "Medellín", "Cali", "Cartagena"]],
  ["Comoros", ["Moroni", "Mutsamudu", "Fomboni"]],
  ["Republic of the Congo", ["Brazzaville", "Pointe-Noire", "Dolisie"]],
  ["Costa Rica", ["San José", "Limón", "Alajuela"]],
  ["Côte d'Ivoire", ["Yamoussoukro", "Abidjan", "Bouaké"]],
  ["Croatia", ["Zagreb", "Split", "Rijeka", "Dubrovnik"]],
  ["Cuba", ["Havana", "Santiago de Cuba", "Camagüey"]],
  ["Cyprus", ["Nicosia", "Limassol", "Larnaca"]],
  ["Czechia", ["Prague", "Brno", "Ostrava"]],
  ["Democratic Republic of the Congo", ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"]],
  ["Denmark", ["Copenhagen", "Aarhus", "Odense"]],
  ["Djibouti", ["Djibouti City", "Ali Sabieh", "Tadjoura"]],
  ["Dominica", ["Roseau", "Portsmouth", "Marigot"]],
  ["Dominican Republic", ["Santo Domingo", "Santiago de los Caballeros", "Punta Cana"]],
  ["Ecuador", ["Quito", "Guayaquil", "Cuenca"]],
  ["Egypt", ["Cairo", "Alexandria", "Giza", "Luxor"]],
  ["El Salvador", ["San Salvador", "Santa Ana", "San Miguel"]],
  ["Equatorial Guinea", ["Malabo", "Bata", "Ebebiyín"]],
  ["Eritrea", ["Asmara", "Keren", "Massawa"]],
  ["Estonia", ["Tallinn", "Tartu", "Narva"]],
  ["Eswatini", ["Mbabane", "Manzini", "Lobamba"]],
  ["Ethiopia", ["Addis Ababa", "Dire Dawa", "Mekelle"]],
  ["Fiji", ["Suva", "Nadi", "Lautoka"]],
  ["Finland", ["Helsinki", "Espoo", "Tampere", "Turku"]],
  ["France", ["Paris", "Marseille", "Lyon", "Nice", "Bordeaux"]],
  ["Gabon", ["Libreville", "Port-Gentil", "Franceville"]],
  ["Gambia", ["Banjul", "Serekunda", "Brikama"]],
  ["Georgia", ["Tbilisi", "Batumi", "Kutaisi"]],
  ["Germany", ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"]],
  ["Ghana", ["Accra", "Kumasi", "Tamale"]],
  ["Greece", ["Athens", "Thessaloniki", "Patras", "Heraklion"]],
  ["Grenada", ["St. George's", "Gouyave", "Grenville"]],
  ["Guatemala", ["Guatemala City", "Quetzaltenango", "Antigua Guatemala"]],
  ["Guinea", ["Conakry", "Nzérékoré", "Kankan"]],
  ["Guinea-Bissau", ["Bissau", "Bafatá", "Gabú"]],
  ["Guyana", ["Georgetown", "Linden", "New Amsterdam"]],
  ["Haiti", ["Port-au-Prince", "Cap-Haïtien", "Gonaïves"]],
  ["Honduras", ["Tegucigalpa", "San Pedro Sula", "La Ceiba"]],
  ["Hungary", ["Budapest", "Debrecen", "Szeged"]],
  ["Iceland", ["Reykjavík", "Kópavogur", "Akureyri"]],
  ["India", ["New Delhi", "Mumbai", "Bangalore", "Kolkata", "Chennai"]],
  ["Indonesia", ["Jakarta", "Surabaya", "Bandung", "Denpasar"]],
  ["Iran", ["Tehran", "Mashhad", "Isfahan", "Shiraz"]],
  ["Iraq", ["Baghdad", "Basra", "Mosul", "Erbil"]],
  ["Ireland", ["Dublin", "Cork", "Galway", "Limerick"]],
  ["Israel", ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"]],
  ["Italy", ["Rome", "Milan", "Naples", "Florence", "Venice"]],
  ["Jamaica", ["Kingston", "Montego Bay", "Spanish Town"]],
  ["Japan", ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo"]],
  ["Jordan", ["Amman", "Zarqa", "Irbid", "Aqaba"]],
  ["Kazakhstan", ["Astana", "Almaty", "Shymkent"]],
  ["Kenya", ["Nairobi", "Mombasa", "Kisumu"]],
  ["Kiribati", ["South Tarawa", "Betio", "Bikenibeu"]],
  ["Kosovo", ["Pristina", "Prizren", "Peja"]],
  ["Kuwait", ["Kuwait City", "Al Ahmadi", "Hawalli"]],
  ["Kyrgyzstan", ["Bishkek", "Osh", "Jalal-Abad"]],
  ["Laos", ["Vientiane", "Luang Prabang", "Pakse"]],
  ["Latvia", ["Riga", "Daugavpils", "Liepāja"]],
  ["Lebanon", ["Beirut", "Tripoli", "Sidon"]],
  ["Lesotho", ["Maseru", "Teyateyaneng", "Mafeteng"]],
  ["Liberia", ["Monrovia", "Gbarnga", "Buchanan"]],
  ["Libya", ["Tripoli", "Benghazi", "Misrata"]],
  ["Liechtenstein", ["Vaduz", "Schaan", "Balzers"]],
  ["Lithuania", ["Vilnius", "Kaunas", "Klaipėda"]],
  ["Luxembourg", ["Luxembourg City", "Esch-sur-Alzette", "Differdange"]],
  ["Madagascar", ["Antananarivo", "Toamasina", "Antsirabe"]],
  ["Malawi", ["Lilongwe", "Blantyre", "Mzuzu"]],
  ["Malaysia", ["Kuala Lumpur", "George Town", "Johor Bahru"]],
  ["Maldives", ["Malé", "Addu City", "Fuvahmulah"]],
  ["Mali", ["Bamako", "Sikasso", "Ségou"]],
  ["Malta", ["Valletta", "Birkirkara", "Sliema"]],
  ["Marshall Islands", ["Majuro", "Ebeye", "Jaluit"]],
  ["Mauritania", ["Nouakchott", "Nouadhibou", "Kiffa"]],
  ["Mauritius", ["Port Louis", "Vacoas-Phoenix", "Curepipe"]],
  ["Mexico", ["Mexico City", "Guadalajara", "Monterrey", "Cancún", "Tijuana"]],
  ["Micronesia", ["Palikir", "Weno", "Kolonia"]],
  ["Moldova", ["Chișinău", "Bălți", "Tiraspol"]],
  ["Monaco", ["Monaco", "Monte Carlo", "La Condamine"]],
  ["Mongolia", ["Ulaanbaatar", "Erdenet", "Darkhan"]],
  ["Montenegro", ["Podgorica", "Nikšić", "Budva"]],
  ["Morocco", ["Rabat", "Casablanca", "Marrakesh", "Fez"]],
  ["Mozambique", ["Maputo", "Beira", "Nampula"]],
  ["Myanmar", ["Naypyidaw", "Yangon", "Mandalay"]],
  ["Namibia", ["Windhoek", "Walvis Bay", "Swakopmund"]],
  ["Nauru", ["Yaren", "Denigomodu", "Aiwo"]],
  ["Nepal", ["Kathmandu", "Pokhara", "Lalitpur"]],
  ["Netherlands", ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"]],
  ["New Zealand", ["Wellington", "Auckland", "Christchurch", "Queenstown"]],
  ["Nicaragua", ["Managua", "León", "Granada"]],
  ["Niger", ["Niamey", "Zinder", "Maradi"]],
  ["Nigeria", ["Abuja", "Lagos", "Kano", "Ibadan"]],
  ["North Korea", ["Pyongyang", "Hamhung", "Chongjin"]],
  ["North Macedonia", ["Skopje", "Bitola", "Ohrid"]],
  ["Norway", ["Oslo", "Bergen", "Trondheim", "Tromsø"]],
  ["Oman", ["Muscat", "Salalah", "Sohar"]],
  ["Pakistan", ["Islamabad", "Karachi", "Lahore", "Peshawar"]],
  ["Palau", ["Ngerulmud", "Koror", "Airai"]],
  ["Palestine", ["Ramallah", "Gaza City", "Hebron", "Bethlehem"]],
  ["Panama", ["Panama City", "San Miguelito", "Colón"]],
  ["Papua New Guinea", ["Port Moresby", "Lae", "Mount Hagen"]],
  ["Paraguay", ["Asunción", "Ciudad del Este", "Encarnación"]],
  ["Peru", ["Lima", "Arequipa", "Cusco", "Trujillo"]],
  ["Philippines", ["Manila", "Quezon City", "Cebu City", "Davao City"]],
  ["Poland", ["Warsaw", "Kraków", "Gdańsk", "Wrocław"]],
  ["Portugal", ["Lisbon", "Porto", "Faro", "Coimbra"]],
  ["Qatar", ["Doha", "Al Rayyan", "Al Wakrah"]],
  ["Romania", ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"]],
  ["Russia", ["Moscow", "Saint Petersburg", "Novosibirsk", "Kazan"]],
  ["Rwanda", ["Kigali", "Huye", "Gisenyi"]],
  ["Saint Kitts and Nevis", ["Basseterre", "Charlestown", "Sandy Point Town"]],
  ["Saint Lucia", ["Castries", "Gros Islet", "Vieux Fort"]],
  ["Saint Vincent and the Grenadines", ["Kingstown", "Georgetown", "Barrouallie"]],
  ["Samoa", ["Apia", "Vaitele", "Faleula"]],
  ["San Marino", ["San Marino", "Serravalle", "Borgo Maggiore"]],
  ["São Tomé and Príncipe", ["São Tomé", "Santo Amaro", "Neves"]],
  ["Saudi Arabia", ["Riyadh", "Jeddah", "Mecca", "Dammam"]],
  ["Senegal", ["Dakar", "Touba", "Thiès"]],
  ["Serbia", ["Belgrade", "Novi Sad", "Niš"]],
  ["Seychelles", ["Victoria", "Anse Boileau", "Beau Vallon"]],
  ["Sierra Leone", ["Freetown", "Bo", "Kenema"]],
  ["Singapore", ["Singapore", "Jurong East", "Woodlands"]],
  ["Slovakia", ["Bratislava", "Košice", "Prešov"]],
  ["Slovenia", ["Ljubljana", "Maribor", "Koper"]],
  ["Solomon Islands", ["Honiara", "Auki", "Gizo"]],
  ["Somalia", ["Mogadishu", "Hargeisa", "Kismayo"]],
  ["South Africa", ["Pretoria", "Johannesburg", "Cape Town", "Durban"]],
  ["South Korea", ["Seoul", "Busan", "Incheon", "Daegu"]],
  ["South Sudan", ["Juba", "Wau", "Malakal"]],
  ["Spain", ["Madrid", "Barcelona", "Valencia", "Seville", "Málaga"]],
  ["Sri Lanka", ["Sri Jayawardenepura Kotte", "Colombo", "Kandy"]],
  ["Sudan", ["Khartoum", "Omdurman", "Port Sudan"]],
  ["Suriname", ["Paramaribo", "Lelydorp", "Nieuw Nickerie"]],
  ["Sweden", ["Stockholm", "Gothenburg", "Malmö", "Uppsala"]],
  ["Switzerland", ["Bern", "Zürich", "Geneva", "Basel"]],
  ["Syria", ["Damascus", "Aleppo", "Homs"]],
  ["Taiwan", ["Taipei", "Kaohsiung", "Taichung"]],
  ["Tajikistan", ["Dushanbe", "Khujand", "Bokhtar"]],
  ["Tanzania", ["Dodoma", "Dar es Salaam", "Arusha", "Zanzibar City"]],
  ["Thailand", ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"]],
  ["Timor-Leste", ["Dili", "Baucau", "Maliana"]],
  ["Togo", ["Lomé", "Sokodé", "Kara"]],
  ["Tonga", ["Nuku'alofa", "Neiafu", "Haveluloto"]],
  ["Trinidad and Tobago", ["Port of Spain", "San Fernando", "Chaguanas"]],
  ["Tunisia", ["Tunis", "Sfax", "Sousse"]],
  ["Turkey", ["Ankara", "Istanbul", "Izmir", "Antalya"]],
  ["Turkmenistan", ["Ashgabat", "Türkmenabat", "Daşoguz"]],
  ["Tuvalu", ["Funafuti", "Vaitupu", "Nanumea"]],
  ["Uganda", ["Kampala", "Gulu", "Mbarara"]],
  ["Ukraine", ["Kyiv", "Kharkiv", "Odesa", "Lviv"]],
  ["United Arab Emirates", ["Abu Dhabi", "Dubai", "Sharjah"]],
  ["United Kingdom", ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow"]],
  ["United States", ["Washington, D.C.", "New York", "Los Angeles", "Chicago", "Austin", "Miami"]],
  ["Uruguay", ["Montevideo", "Salto", "Punta del Este"]],
  ["Uzbekistan", ["Tashkent", "Samarkand", "Bukhara"]],
  ["Vanuatu", ["Port Vila", "Luganville", "Isangel"]],
  ["Vatican City", ["Vatican City"]],
  ["Venezuela", ["Caracas", "Maracaibo", "Valencia"]],
  ["Vietnam", ["Hanoi", "Ho Chi Minh City", "Da Nang"]],
  ["Yemen", ["Sanaa", "Aden", "Taiz"]],
  ["Zambia", ["Lusaka", "Kitwe", "Ndola"]],
  ["Zimbabwe", ["Harare", "Bulawayo", "Mutare"]],
];

const countryOf = (name) => WORLD.find((c) => c[0] === name) || null;
const capitalOf = (name) => (countryOf(name) || [null, [null]])[1][0];

/// Moving costs more the farther the destination is from home (roughly, by region).
function emigrationCost(L, country) {
  return country === L.country ? 2000 : 5000;
}

function emigrateTo(L, country, city) {
  if (L.age < 18) return out(L, "Emigrate", "I'm too young to move abroad by myself.", false);
  const cost = emigrationCost(L, country);
  if (L.money < cost) return out(L, "Emigrate", `I need ${formatMoney(cost)} to move to ${city}.`, false);
  if (country !== L.country && L.criminalRecord.length >= 3 && roll(0.4)) {
    return out(L, "Visa Denied", `🛂 ${country} denied my visa because of my criminal record.`);
  }
  L.money -= cost;
  const domestic = country === L.country;
  L.city = city;
  L.country = country;
  if (!domestic && L.job) { record(L, `I left my job as a ${L.job.title}.`); L.job = null; }
  for (const p of L.relationships) if (p.isAlive && !p.species && !isRomantic(p.kind) && p.kind !== "child") p.bond = Math.max(0, p.bond - (domestic ? 3 : 8));
  adjust(L, { happiness: 8 });
  return out(L, domestic ? "Moved" : "Emigrated", domestic ? `🚚 I moved to ${city}.` : `✈️ I emigrated to ${city}, ${country}!`);
}
